#!/usr/bin/env python3
from starShift import star_shift
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('-path', required=True, help="Path to .starShift file")
args = parser.parse_args()

result = star_shift(args.path)
print(result)